### ISSUE TITLE
Where's tunnelkit

### ISSUE THREAD

**Issue by hufengiOS** [passepartoutvpn/passepartout-app#504]
hello This code is not accessible, why is it closed?
https://github.com/passepartoutvpn/tunnelkit.git

**Comment by hsklia** [comment]
Please revert the project

**Comment by keeshux** [comment]
After noticing a flattering amount of people:

- Silently abusing the license of TunnelKit (GPL), which is the result of 7 years of hard work given out _for free_
- Contributing absolutely nothing to the project
- Creating issues without ever offering PRs/solutions, or searching for duplicates before
- Entitled to complain without offering anything in exchange, not even good manners

I've eventually decided to take it down, as simple as that. I'm sure that the good people out there will understand my decision.

**Comment by hufengiOS** [comment]
I'm sorry to interrupt your life and work because of the problems we encountered.

**Comment by hsklia** [comment]
I have an idea: to keep the project source closed and offer it for sale along with dedicated support services.
So the project will be live you can get money from the project.
