### ISSUE TITLE
Can't build app, tunnelkit not available

### ISSUE THREAD

**Issue by SephSG** [passepartoutvpn/passepartout-app#508]
# Summary
Can't build app, spm module "tunnelkit" not available. Also page https://github.com/passepartoutvpn/tunnelkit/ return 404 error.

### Relevant logs and/or screenshots
<img width="585" alt="Screenshot 2024-07-03 at 18 24 33" src="https://github.com/passepartoutvpn/passepartout-app/assets/48690359/c12d7023-da64-432b-accb-5681542edff6">

**Comment by keeshux** [comment]
This is intentional. Going forward, the TunnelKit dependency will be built privately or mocked for public builds. The repository is and will stay private.
