### ISSUE TITLE
Non-Retina Support

### ISSUE THREAD

**Issue by revunix** [passepartoutvpn/passepartout-app#509]
Hello,

Would it be possible for them to add support for non-retina displays? The app looks pretty blurry on my 2K monitor. I would like to buy it, but unfortunately not like this.

**Comment by keeshux** [comment]
Would you post a screenshot? We're talking about macOS right?

**Comment by revunix** [comment]
Yes, I'm talking about macOS. A screenshot is useless in this case because on a screenshot look it normal. Its is a thing with this universal catalyst style apps. This is a problem with the HiDPI and font size. Maybe make the app bigger for non-retina devices. For example, the "Mona for Mastodon"-App uses tricks like this here to fix this problem because there are using also a catalyst app for the Mac.

![SCR-20240710-piyo](https://github.com/passepartoutvpn/passepartout-app/assets/4172418/578e3f29-b0ed-48a6-aff3-d8e041b187f0)

**Comment by keeshux** [comment]
Gotcha. Well, I'm (slooowly) rewriting the app to be native macOS, no more Catalyst. I think that by that time the issue will seamlessly go away.
